name = "tetrashop-social-analytics"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"
workers_dev = true

[vars]
ENVIRONMENT = "production"
VERSION = "2.0.0"
